(function(seedData){
    seedData.initialPc = [
        {
            "id":"4816",
            "status":"active",
            "name":"Samsung Chromebook 2 11.6 Inch Laptop (Intel Celeron, 2 GB, 16 GB SSD, Silver)",
            "price":"189.88",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41g63QKnsUL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 21:01 PST",
            "url":"http:\/\/www.amazon.com\/Samsung-Chromebook-Laptop-Celeron-Silver\/dp\/B00NJGRLUY%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00NJGRLUY",
            "region":"com",
            "popularity":"100",
            "needs_update":"0",
            "att_gpu":"Intel HD",
            "att_screen_size":"11.6",
            "att_ram":"2",
            "att_storage":"16",
            "att_weight":"2.65",
            "att_brand":"Samsung",
            "att_cpu":"Intel Celeron",
            "att_ssd":"16",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_touchscreen":"0",
            "att_discrete_gpu":"0",
            "att_base_name":"Samsung Chromebook 2",
            "att_screen_surface":"Matte",
            "att_os":"Chrome OS",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"6604",
            "status":"active",
            "name":"Toshiba Satellite C55-C5241 15.6 Inch Laptop (Intel Core i5, 8 GB, 1TB HDD), Black",
            "price":"449.99",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/51f%2BD2Fv3-L._SL160_.jpg",
            "last_update":"Jan 7, 2016, 21:42 PST",
            "url":"http:\/\/www.amazon.com\/Toshiba-Satellite-C55-C5241-Laptop-Intel\/dp\/B010SBAJDS%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB010SBAJDS",
            "region":"com",
            "popularity":"100",
            "needs_update":"0",
            "att_brand":"Toshiba",
            "att_base_name":"Toshiba Satellite C55-C5241",
            "att_screen_size":"15.6",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_screen_surface":"glossy",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i5",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD 5500",
            "att_ram":"8",
            "att_ssd":"0",
            "att_storage":"1000",
            "att_weight":"4.8",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"6605",
            "status":"active",
            "name":"ASUS F555LA-AB31 15.6-inch Full-HD Laptop (Core i3, 4GB RAM, 500GB HDD) with Windows 10",
            "price":"349.99",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41uXvMCE9UL._SL160_.jpg",
            "last_update":"Jan 8, 2016, 00:07 PST",
            "url":"http:\/\/www.amazon.com\/F555LA-AB31-15-6-inch-Full-HD-Laptop-Windows\/dp\/B011KFQASE%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB011KFQASE",
            "region":"com",
            "popularity":"100",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"Asus F555LA-AB31",
            "att_screen_size":"15.6",
            "att_pixels_x":"1920",
            "att_pixels_y":"1080",
            "att_screen_surface":"matte",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i3",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_ram":"4",
            "att_ssd":"0",
            "att_storage":"500",
            "att_weight":"5.1",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"6606",
            "status":"active",
            "name":"Acer Chromebook, 11.6-Inch, CB3-111-C670 (Intel Celeron, 2GB, 16GB SSD, White)",
            "price":"178.99",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/51M-7YIZPhL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 21:34 PST",
            "url":"http:\/\/www.amazon.com\/Acer-Chromebook-11-6-Inch-CB3-111-C670-Celeron\/dp\/B00MMLV7VQ%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00MMLV7VQ",
            "region":"com",
            "popularity":"100",
            "needs_update":"0",
            "att_brand":"Acer",
            "att_base_name":"Acer Chromebook 11",
            "att_screen_size":"11.6",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_screen_surface":"matte",
            "att_touchscreen":"0",
            "att_cpu":"Intel Celeron",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_ram":"2",
            "att_ssd":"16",
            "att_storage":"16",
            "att_weight":"2.4",
            "att_os":"Chrome OS",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"7875",
            "status":"active",
            "name":"Dell Inspiron 15 i5558-5718SLV Signature Edition Laptop - 15.6\" 1080p Full HD Touchscreen, Intel Core i5-4210U, 8GB RAM, 1TB HDD, Windows 10 Home (Silver)",
            "price":"504.88",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/5115t8Qz-eL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 08:16 PST",
            "url":"http:\/\/www.amazon.com\/Dell-Inspiron-15-i5558-5718SLV-Signature\/dp\/B018LH6FWK%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB018LH6FWK",
            "region":"com",
            "popularity":"100",
            "needs_update":"0",
            "att_brand":"Dell",
            "att_base_name":"Dell Inspiron 15 i5558-5718SLV",
            "att_screen_size":"15.6",
            "att_pixels_x":"1920",
            "att_pixels_y":"1080",
            "att_screen_surface":"Glossy",
            "att_touchscreen":"1",
            "att_cpu":"Intel Core i5",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD 4400",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"8",
            "att_ssd":"0",
            "att_storage":"1000",
            "att_weight":"5.3"
        },
        {
            "id":"6352",
            "status":"active",
            "name":"ASUS X551MA 15.6 Inch Laptop (Intel Celeron, 4 GB, 500GB HDD, Black) - Free Upgrade to Windows 10",
            "price":"269.00",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41vvI6UQs9L._SL160_.jpg",
            "last_update":"Jan 7, 2016, 08:37 PST",
            "url":"http:\/\/www.amazon.com\/X551MA-Laptop-Intel-Celeron-500GB\/dp\/B00SV72ZA2%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00SV72ZA2",
            "region":"com",
            "popularity":"99",
            "needs_update":"0",
            "att_screen_size":"15.6",
            "att_ram":"4",
            "att_storage":"500",
            "att_weight":"4.7",
            "att_brand":"Asus",
            "att_cpu":"Intel Celeron",
            "att_base_name":"ASUS X551MAV-EB01-B(S)",
            "att_gpu":"Intel HD",
            "att_discrete_gpu":"0",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_ssd":"0",
            "att_touchscreen":"0",
            "att_screen_surface":"Glossy",
            "att_os":"Windows",
            "att_os_details":"Windows 8.1",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"6611",
            "status":"active",
            "name":"Apple MacBook Air MJVE2LL\/A 13-inch Laptop (1.6 GHz Intel Core i5,4GB RAM,128 GB SSD Hard Drive, Mac OS X)",
            "price":"908.88",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/31nkqgDl0OL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 22:59 PST",
            "url":"http:\/\/www.amazon.com\/Apple-MacBook-MJVE2LL-13-inch-Laptop\/dp\/B00VJ1P7TS%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00VJ1P7TS",
            "region":"com",
            "popularity":"99",
            "needs_update":"0",
            "att_brand":"Apple",
            "att_base_name":"Apple MacBook Air MJVE2LL\/A",
            "att_screen_size":"13.3",
            "att_pixels_x":"1440",
            "att_pixels_y":"900",
            "att_screen_surface":"glossy",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i5",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD Graphics 6000",
            "att_ram":"4",
            "att_ssd":"128",
            "att_storage":"128",
            "att_weight":"3"
        },
        {
            "id":"6684",
            "status":"active",
            "name":"ASUS Zenbook UX305LA 13.3-Inch Laptop (Intel Core i5, 8GB RAM, 256 GB SSD, Windows 10), Titanium Gold",
            "price":"749.99",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/51C1sNaz87L._SL160_.jpg",
            "last_update":"Jan 7, 2016, 17:51 PST",
            "url":"http:\/\/www.amazon.com\/Zenbook-UX305LA-13-3-Inch-Windows-Titanium\/dp\/B013KKANTE%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB013KKANTE",
            "region":"com",
            "popularity":"99",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"Asus Zenbook UX305LA-AB51",
            "att_screen_size":"13.3",
            "att_pixels_x":"1920",
            "att_pixels_y":"1080",
            "att_screen_surface":"matte",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i5",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD 5500",
            "att_ram":"8",
            "att_ssd":"256",
            "att_storage":"256",
            "att_weight":"2.9",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"7269",
            "status":"active",
            "name":"HP Stream 13.3-Inch Laptop (Intel Celeron, 2 GB RAM, 32 GB SSD, Cobalt Blue) with Office 365 Personal for One Year",
            "price":"229.00",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/512dY%2BmlmlL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 11:32 PST",
            "url":"http:\/\/www.amazon.com\/HP-Stream-13-3-Inch-Celeron-Personal\/dp\/B015CQ8PNA%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB015CQ8PNA",
            "region":"com",
            "popularity":"99",
            "needs_update":"0",
            "att_brand":"HP",
            "att_base_name":"HP Stream 13-c110nr",
            "att_screen_size":"13.3",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_screen_surface":"matte",
            "att_touchscreen":"0",
            "att_cpu":"Intel Celeron",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"2",
            "att_ssd":"32",
            "att_storage":"32",
            "att_weight":"3.42"
        },
        {
            "id":"7272",
            "status":"active",
            "name":"HP Stream 11-r010nr 11.6-Inch Notebook (Intel Celeron Processor, 2GB RAM, 32 GB Hard Drive, Windows 10 Home 64- Bit), Cobalt Blue",
            "price":"199.99",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/512dY%2BmlmlL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 18:19 PST",
            "url":"http:\/\/www.amazon.com\/HP-11-r010nr-11-6-Inch-Notebook-Processor\/dp\/B015CQ8SGE%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB015CQ8SGE",
            "region":"com",
            "popularity":"99",
            "needs_update":"0",
            "att_brand":"HP",
            "att_base_name":"HP Stream 11-r010nr",
            "att_screen_size":"11.6",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_screen_surface":"Matte",
            "att_touchscreen":"0",
            "att_cpu":"Intel Celeron",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"2",
            "att_ssd":"32",
            "att_storage":"32",
            "att_weight":"2.6"
        },
        {
            "id":"7507",
            "status":"active",
            "name":"Dell Inspiron i7559-763BLK 15.6\" Full-HD Gaming Laptop (Core i5, 8GB RAM, 256GB SSD, NVIDIA GeForce GTX960M) with Windows 10",
            "price":"799.99",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41BrD2bCAeL._SL160_.jpg",
            "last_update":"Jan 8, 2016, 02:51 PST",
            "url":"http:\/\/www.amazon.com\/Dell-Inspiron-i7559-763BLK-Full-HD-GeForce\/dp\/B015PYYDMQ%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB015PYYDMQ",
            "region":"com",
            "popularity":"99",
            "needs_update":"0",
            "att_brand":"Dell",
            "att_base_name":"Dell Inspiron i7559-763BLK",
            "att_screen_size":"15.6",
            "att_pixels_x":"1920",
            "att_pixels_y":"1080",
            "att_screen_surface":"Matte",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i5",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"1",
            "att_gpu":"NVIDIA GeForce GTX960M",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"8",
            "att_ssd":"256",
            "att_storage":"256",
            "att_weight":"5.67"
        },
        {
            "id":"3857",
            "status":"active",
            "name":"Toshiba CB35-B3340 13.3 Inch Chromebook (Intel Celeron, 4GB, 16GB SSD, Silver) Full HD-Screen",
            "price":"291.46",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41SJTSRFTRL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 20:29 PST",
            "url":"http:\/\/www.amazon.com\/Toshiba-CB35-B3340-Chromebook-Celeron-HD-Screen\/dp\/B00N99FXIS%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00N99FXIS",
            "region":"com",
            "popularity":"98",
            "needs_update":"0",
            "att_ram":"4",
            "att_screen_size":"13.3",
            "att_pixels_x":"1920",
            "att_pixels_y":"1080",
            "att_weight":"2.95",
            "att_gpu":"Intel HD",
            "att_brand":"Toshiba",
            "att_cpu":"Intel Celeron",
            "att_ssd":"16",
            "att_touchscreen":"0",
            "att_storage":"16",
            "att_discrete_gpu":"0",
            "att_base_name":"Toshiba CB35-B3340",
            "att_screen_surface":"Glossy",
            "att_os":"Chrome OS",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"6624",
            "status":"active",
            "name":"ASUS Chromebook Flip 10.1-Inch Convertible 2 in 1 Touchscreen (Rockchip, 4 GB, 16GB SSD, Silver)",
            "price":"268.16",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41CsYRgFTSL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 20:50 PST",
            "url":"http:\/\/www.amazon.com\/Chromebook-10-1-Inch-Convertible-Touchscreen-Rockchip\/dp\/B00ZS4HK0Q%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00ZS4HK0Q",
            "region":"com",
            "popularity":"98",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"Asus Chromebook Flip C100PA",
            "att_screen_size":"10.1",
            "att_pixels_x":"1280",
            "att_pixels_y":"800",
            "att_screen_surface":"glossy",
            "att_touchscreen":"1",
            "att_cpu":"Rockchip",
            "att_discrete_gpu":"0",
            "att_gpu":"Rockchip Mali T764",
            "att_ram":"4",
            "att_ssd":"16",
            "att_storage":"16",
            "att_weight":"2",
            "att_os":"Chrome OS",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"7076",
            "status":"active",
            "name":"Acer Aspire One Cloudbook, 11-Inch HD, 32GB, Windows 10, Gray (AO1-131-C9PM) includes Office 365 Personal - 1 year",
            "price":"167.93",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41O52GmrmJL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 15:02 PST",
            "url":"http:\/\/www.amazon.com\/Acer-Cloudbook-11-Inch-AO1-131-C9PM-Personal\/dp\/B0149QDD1S%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB0149QDD1S",
            "region":"com",
            "popularity":"98",
            "needs_update":"0",
            "att_brand":"Acer",
            "att_base_name":"Acer Aspire One Cloudbook 11 AO1-131",
            "att_screen_size":"11.6",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_screen_surface":"glossy",
            "att_touchscreen":"0",
            "att_cpu":"Intel Celeron",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_ram":"2",
            "att_ssd":"32",
            "att_storage":"32",
            "att_weight":"2.54",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"7420",
            "status":"active",
            "name":"ASUS K501UX 15-inch Gaming Laptop (Intel Core i7 Processor, 8GB RAM, 256GB SSD Hard Drive, Windows 10 (64 bit)), Black\/Silver Metal",
            "price":"779.00",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41WN8y6bohL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 08:24 PST",
            "url":"http:\/\/www.amazon.com\/K501UX-15-inch-Gaming-Processor-Windows\/dp\/B0146DD02G%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB0146DD02G",
            "region":"com",
            "popularity":"98",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"Asus K501UX",
            "att_screen_size":"15.6",
            "att_pixels_x":"1920",
            "att_pixels_y":"1280",
            "att_screen_surface":"Matte",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i7",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"1",
            "att_gpu":"NVIDIA GeForce GTX 950M",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"8",
            "att_ssd":"256",
            "att_storage":"256",
            "att_weight":"4.4"
        },
        {
            "id":"7223",
            "status":"active",
            "name":"Toshiba Chromebook 2 - 2015 Edition (CB35-C3300) Full HD, Backlit Keyboard",
            "price":"329.99",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41%2BEvoK3rAL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 20:47 PST",
            "url":"http:\/\/www.amazon.com\/Toshiba-Chromebook-Edition-CB35-C3300-Keyboard\/dp\/B015806LMM%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB015806LMM",
            "region":"com",
            "popularity":"97",
            "needs_update":"0",
            "att_brand":"Toshiba",
            "att_base_name":"Toshiba Chromebook 2 CB35-C3300",
            "att_screen_size":"13.3",
            "att_pixels_x":"1920",
            "att_pixels_y":"1080",
            "att_screen_surface":"glossy",
            "att_touchscreen":"0",
            "att_cpu":"Intel Celeron",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_ram":"4",
            "att_ssd":"16",
            "att_storage":"16",
            "att_weight":"2.9",
            "att_os":"Chrome OS",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"7425",
            "status":"active",
            "name":"HP Stream 13.3-Inch Laptop (Intel Celeron, 2 GB RAM, 32 GB SSD, Violet Purple) with Office 365 Personal for One Year",
            "price":"229.99",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/51mluqBXywL._SL160_.jpg",
            "last_update":"Jan 8, 2016, 01:58 PST",
            "url":"http:\/\/www.amazon.com\/HP-Stream-13-3-Inch-Celeron-Personal\/dp\/B015CQ8RO2%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB015CQ8RO2",
            "region":"com",
            "popularity":"97",
            "needs_update":"0",
            "att_brand":"HP",
            "att_base_name":"HP Stream 13-c120nr",
            "att_screen_size":"13.3",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_touchscreen":"0",
            "att_cpu":"Intel Celeron",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"2",
            "att_ssd":"32",
            "att_storage":"32",
            "att_weight":"3.42",
            "att_screen_surface":"Matte"
        },
        {
            "id":"8064",
            "status":"active",
            "name":"ASUS ROG GL551JW-AH71(WX) 15-Inch Gaming Laptop, Discrete GPU GeForce GTX 960M 2GB VRAM, 8GB, 256G SSD storage (ROG Black)",
            "price":"799.00",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41pgEAuPT5L._SL160_.jpg",
            "last_update":"Jan 7, 2016, 13:56 PST",
            "url":"http:\/\/www.amazon.com\/GL551JW-AH71-WX-15-Inch-Discrete-GeForce\/dp\/B017NGH4DY%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB017NGH4DY",
            "region":"com",
            "popularity":"97",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"Asus ROG GL551JW-AH71(WX)",
            "att_screen_size":"15.6",
            "att_pixels_x":"1920",
            "att_pixels_y":"1080",
            "att_screen_surface":"Matte",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i7",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"1",
            "att_gpu":"NVIDIA GeForce GTX 960M",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"8",
            "att_ssd":"256",
            "att_storage":"256",
            "att_weight":"6"
        },
        {
            "id":"8065",
            "status":"active",
            "name":"HP 15-F211WM Touchscreen Laptop Dual Core 4GB 500GB DVD-RW 15.6\" HDMI Win 10",
            "price":"304.66",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/4184Gj21ZsL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 15:02 PST",
            "url":"http:\/\/www.amazon.com\/HP-15-F211WM-Touchscreen-Laptop-DVD-RW\/dp\/B017PE2LMS%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB017PE2LMS",
            "region":"com",
            "popularity":"97",
            "needs_update":"0",
            "att_brand":"HP",
            "att_base_name":"HP 15-f211wm",
            "att_screen_size":"15.6",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_screen_surface":"Glossy",
            "att_touchscreen":"1",
            "att_cpu":"Intel Celeron",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"4",
            "att_ssd":"0",
            "att_storage":"500",
            "att_weight":"5.05"
        },
        {
            "id":"8069",
            "status":"active",
            "name":"HP Pavilion 15.6\" Flagship Laptop, 6th Gen Skylake Intel i7-6700HQ Quad-Core Processor(6M Cache, up to 3.5 GHz), FHD IPS Touchscreen, 8GB DDR3, 1TB HDD, DVD, HDMI, 802.11AC, Windows 10",
            "price":"647.96",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/51hQ41HotlL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 14:05 PST",
            "url":"http:\/\/www.amazon.com\/HP-i7-6700HQ-Quad-Core-Processor-Touchscreen\/dp\/B018YIGHVK%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB018YIGHVK",
            "region":"com",
            "popularity":"97",
            "needs_update":"0",
            "att_brand":"HP",
            "att_base_name":"HP Pavilion 15-ab292nr",
            "att_screen_size":"15.6",
            "att_pixels_x":"1920",
            "att_pixels_y":"1080",
            "att_screen_surface":"Glossy",
            "att_touchscreen":"1",
            "att_cpu":"Intel Core i7",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD 530",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"8",
            "att_ssd":"0",
            "att_storage":"1000",
            "att_weight":"5.25"
        },
        {
            "id":"4066",
            "status":"active",
            "name":"Samsung Chromebook (Wi-Fi, 11.6-Inch) - Silver (Certified Refurbished)",
            "price":"149.99",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41ncpjt3T9L._SL160_.jpg",
            "last_update":"Jan 7, 2016, 19:38 PST",
            "url":"http:\/\/www.amazon.com\/Samsung-Chromebook-Wi-Fi-11-6-Inch-Refurbished\/dp\/B00M9K7L8S%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00M9K7L8S",
            "region":"com",
            "popularity":"96",
            "needs_update":"0",
            "att_gpu":"Intel HD",
            "att_screen_size":"11.6",
            "att_ram":"2",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_weight":"2.43",
            "att_brand":"Samsung",
            "att_cpu":"Samsung Exynos",
            "att_ssd":"16",
            "att_touchscreen":"0",
            "att_storage":"16",
            "att_discrete_gpu":"0",
            "att_base_name":"Samsung Chromebook (Wi-Fi, 11.6-Inch)",
            "att_screen_surface":"Matte",
            "att_os":"Chrome OS",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"7415",
            "status":"active",
            "name":"ASUS Transformer Book T100HA-C4-GR 10.1-inch 2 in 1 Touchscreen Laptop",
            "price":"294.00",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41RrOVqFQuL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 09:59 PST",
            "url":"http:\/\/www.amazon.com\/Transformer-T100HA-C4-GR-10-1-inch-Touchscreen-Laptop\/dp\/B014854RGK%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB014854RGK",
            "region":"com",
            "popularity":"96",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"Asus Transformer Book T100HA-C4-GR",
            "att_screen_size":"10.1",
            "att_pixels_x":"1280",
            "att_pixels_y":"800",
            "att_screen_surface":"Glossy",
            "att_touchscreen":"1",
            "att_cpu":"Intel Atom",
            "att_detachable_keyboard":"1",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"4",
            "att_ssd":"64",
            "att_storage":"64",
            "att_weight":"2.28"
        },
        {
            "id":"7500",
            "status":"active",
            "name":"ASUS F555UA-EH71 15.6 Inch, Intel Core i7, 8GB, 1TB HDD Laptop, Windows 10 (64bit)",
            "price":"564.99",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41TwwPbHIlL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 16:22 PST",
            "url":"http:\/\/www.amazon.com\/F555UA-EH71-Intel-Laptop-Windows-64bit\/dp\/B014LE6A6I%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB014LE6A6I",
            "region":"com",
            "popularity":"96",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"Asus F555UA",
            "att_screen_size":"15.6",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_screen_surface":"Glossy",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i7",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"8",
            "att_ssd":"0",
            "att_storage":"1000",
            "att_weight":"5.1"
        },
        {
            "id":"7504",
            "status":"active",
            "name":"ASUS ROG GL552VW-DH71 15-Inch Gaming Laptop, Discrete GPU GeForce GTX 960M 2GB VRAM, 16GB DDR4, 1TB (ROG Metallic)",
            "price":"999.00",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41JuUFBstEL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 08:17 PST",
            "url":"http:\/\/www.amazon.com\/GL552VW-DH71-15-Inch-Discrete-GeForce-Metallic\/dp\/B01578ZKPO%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB01578ZKPO",
            "region":"com",
            "popularity":"96",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"Asus ROG GL552VW-DH71",
            "att_screen_size":"15.6",
            "att_pixels_x":"1920",
            "att_pixels_y":"1080",
            "att_screen_surface":"Matte",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i7",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"1",
            "att_gpu":"NVIDIA GeForce GTX 960M",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"16",
            "att_ssd":"0",
            "att_storage":"1000",
            "att_weight":"5.6"
        },
        {
            "id":"7874",
            "status":"active",
            "name":"Asus X553SA-BHCLN10 15.6 Inch Laptop (Intel Celeron Processor, 4GB, 500 GB HDD, Windows 10, Black)",
            "price":"245.69",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41BUqjljNDL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 10:53 PST",
            "url":"http:\/\/www.amazon.com\/Asus-X553SA-BHCLN10-Celeron-Processor-Windows\/dp\/B018DYW7VE%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB018DYW7VE",
            "region":"com",
            "popularity":"96",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"Asus X553SA-BHCLN10",
            "att_screen_size":"15.6",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_touchscreen":"0",
            "att_cpu":"Intel Celeron",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"4",
            "att_ssd":"0",
            "att_storage":"500",
            "att_weight":"4.8"
        },
        {
            "id":"8066",
            "status":"active",
            "name":"Asus - 15.6\" Laptop \/ Intel Core i3-5020U \/ 4GB Memory \/ 1TB Hard Drive \/ DVD\u00b1RW\/CD-RW \/ HD Webcam \/ Windows 10 - Warm Golden Gradient",
            "price":"323.59",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41%2BUFnJQEgL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 16:29 PST",
            "url":"http:\/\/www.amazon.com\/Asus-Laptop-i3-5020U-Windows-Gradient\/dp\/B0181OV6JA%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB0181OV6JA",
            "region":"com",
            "popularity":"96",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"Asus X555LA-HI31103J",
            "att_screen_size":"15.6",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i3",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"0",
            "att_gpu":"Intel HD 5500",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"4",
            "att_ssd":"0",
            "att_storage":"1000",
            "att_weight":"5.1"
        },
        {
            "id":"6452",
            "status":"active",
            "name":"ASUS Chromebook Flip 10.1-Inch Convertible 2 in 1 Touchscreen (Rockchip, 2 GB, 16GB SSD, Silver)",
            "price":"238.84",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41CsYRgFTSL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 13:06 PST",
            "url":"http:\/\/www.amazon.com\/Chromebook-10-1-Inch-Convertible-Touchscreen-Rockchip\/dp\/B00YY3X678%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00YY3X678",
            "region":"com",
            "popularity":"95",
            "needs_update":"0",
            "att_screen_size":"10.1",
            "att_ram":"2",
            "att_pixels_x":"1280",
            "att_pixels_y":"800",
            "att_weight":"2",
            "att_brand":"Asus",
            "att_ssd":"16",
            "att_touchscreen":"1",
            "att_base_name":"ASUS Chromebook Flip C100PA",
            "att_storage":"16",
            "att_cpu":"Rockchip",
            "att_gpu":"ARM Mali T764",
            "att_discrete_gpu":"0",
            "att_screen_surface":"Glossy",
            "att_os":"Chrome OS",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"7495",
            "status":"active",
            "name":"Acer Aspire E5-573G 15.6-Inch Gaming Laptop (Intel Core i5 5200U, 8GB, 1TB, NVIDIA GeForce 940M 2GB, Windows 10 Home)",
            "price":"558.00",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41LAesMrPNL._SL160_.jpg",
            "last_update":"Jan 8, 2016, 00:56 PST",
            "url":"http:\/\/www.amazon.com\/Acer-E5-573G-15-6-Inch-GeForce-Windows\/dp\/B012IBOCRU%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB012IBOCRU",
            "region":"com",
            "popularity":"95",
            "needs_update":"0",
            "att_brand":"Acer",
            "att_base_name":"Acer Aspire E 15 E5-573G",
            "att_screen_size":"15.6",
            "att_pixels_x":"1920",
            "att_pixels_y":"1080",
            "att_screen_surface":"Glossy",
            "att_touchscreen":"0",
            "att_cpu":"Intel Core i5",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"1",
            "att_gpu":"NVIDIA GeForce 940M",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_ram":"8",
            "att_ssd":"0",
            "att_storage":"1000",
            "att_weight":"5.29"
        },
        {
            "id":"7506",
            "status":"active",
            "name":"Asus X550ZA-WH11 15.6-Inch Laptop (AMD Quad Core A10-7400P 2.5GHz processor, 8 GB DDR3 RAM, 1000 GB Hard Drive, Windows 10), Dark Grey",
            "price":"449.00",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/41qzHiPTPRL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 15:07 PST",
            "url":"http:\/\/www.amazon.com\/Asus-X550ZA-WH11-15-6-Inch-A10-7400P-processor\/dp\/B0158XJGJ4%3FSubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB0158XJGJ4",
            "region":"com",
            "popularity":"95",
            "needs_update":"0",
            "att_brand":"Asus",
            "att_base_name":"ASUS X550ZA",
            "att_screen_size":"15.6",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_screen_surface":"matte",
            "att_touchscreen":"0",
            "att_cpu":"AMD A10",
            "att_discrete_gpu":"0",
            "att_gpu":"AMD Radeon R6",
            "att_ram":"8",
            "att_ssd":"0",
            "att_storage":"1000",
            "att_weight":"5.1",
            "att_os":"Windows",
            "att_os_details":"Windows 10",
            "att_detachable_keyboard":"0"
        },
        {
            "id":"8057",
            "status":"active",
            "name":"HP Chromebook 14 G3 14\" LED Chromebook - NVIDIA Tegra K1 Quad-core (4 Core) 2.10 GHz K4K11UT#ABA",
            "price":"299.88",
            "image":"http:\/\/ecx.images-amazon.com\/images\/I\/31-bt5DbeoL._SL160_.jpg",
            "last_update":"Jan 7, 2016, 13:55 PST",
            "url":"http:\/\/www.amazon.com\/HP-Chromebook-14-LED-Quad-core\/dp\/B00VPJY7NQ%3Fpsc%3D1%26SubscriptionId%3DAKIAJ76EIXAV3V6D6JEQ%26tag%3Dglobalnetwork-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00VPJY7NQ",
            "region":"com",
            "popularity":"95",
            "needs_update":"0",
            "att_brand":"HP",
            "att_base_name":"HP Chromebook 14 G3",
            "att_screen_size":"14",
            "att_pixels_x":"1366",
            "att_pixels_y":"768",
            "att_screen_surface":"Matte",
            "att_touchscreen":"0",
            "att_cpu":"NVIDIA Tegra K1",
            "att_detachable_keyboard":"0",
            "att_discrete_gpu":"0",
            "att_gpu":"NVIDIA Kepler",
            "att_os":"Chrome OS",
            "att_ram":"4",
            "att_ssd":"16",
            "att_storage":"16",
            "att_weight":"3.78"
        }
    //    {
    //    "name": "Toshiba Satellite C55-C5241 15.6 Inch Laptop (Intel Core i5, 8 GB, 1TB HDD), Black",
    //    "price": "449.99",
    //    "image": "http:\/\/ecx.images-amazon.com\/images\/I\/51f%2BD2Fv3-L._SL160_.jpg",
    //    "att_brand": "Toshiba",
    //    "att_screen_size": "15.6",
    //    "att_pixels_x": "1366",
    //    "att_pixels_y": "768",
    //    "att_touchscreen": false,
    //    "att_cpu": "Intel Core i5",
    //    "att_gpu": "Intel HD 5500",
    //    "att_ram": "8",
    //    "att_ssd": "0",
    //    "att_storage": "1000",
    //    "att_weight": "4.8",
    //    "att_os": {
    //        "brand": "windows",
    //        "version": "10"
    //    }
    //},
    //    {
    //        "name": "ASUS F555LA-AB31 15.6-inch Full-HD Laptop (Core i3, 4GB RAM, 500GB HDD) with Windows 10",
    //        "price": "349.99",
    //        "image": "http:\/\/ecx.images-amazon.com\/images\/I\/41uXvMCE9UL._SL160_.jpg",
    //        "att_brand": "Asus",
    //        "att_screen_size": "15.6",
    //        "att_pixels_x": "1920",
    //        "att_pixels_y": "1080",
    //        "att_touchscreen": false,
    //        "att_cpu": "Intel Core i3",
    //        "att_gpu": "Intel HD",
    //        "att_ram": "4",
    //        "att_ssd": "0",
    //        "att_storage": "500",
    //        "att_weight": "5.1",
    //        "att_os": {
    //            "brand": "windows",
    //            "version": "10"
    //        }
    //    },
    //    {
    //        "name": "Acer Chromebook, 11.6-Inch, CB3-111-C670 (Intel Celeron, 2GB, 16GB SSD, White)",
    //        "price": "175.26",
    //        "image": "http:\/\/ecx.images-amazon.com\/images\/I\/51M-7YIZPhL._SL160_.jpg",
    //        "att_brand": "Acer",
    //        "att_screen_size": "11.6",
    //        "att_pixels_x": "1366",
    //        "att_pixels_y": "768",
    //        "att_touchscreen": false,
    //        "att_cpu": "Intel Celeron",
    //        "att_gpu": "Intel HD",
    //        "att_ram": "2",
    //        "att_ssd": "16",
    //        "att_storage": "16",
    //        "att_weight": "2.4",
    //        "att_os": {
    //            "brand": "Chrome OS",
    //            "version": "2"
    //        }
    //    },
    //    {
    //        "name": "Dell Inspiron 15 i5558-5718SLV Signature Edition Laptop - 15.6\" 1080p Full HD Touchscreen, Intel Core i5-4210U, 8GB RAM, 1TB HDD, Windows 10 Home (Silver)",
    //        "price": "488.97",
    //        "image": "http:\/\/ecx.images-amazon.com\/images\/I\/5115t8Qz-eL._SL160_.jpg",
    //        "att_brand": "Dell",
    //        "att_screen_size": "15.6",
    //        "att_pixels_x": "1920",
    //        "att_pixels_y": "1080",
    //        "att_touchscreen": true,
    //        "att_cpu": "Intel Core i5",
    //        "att_gpu": "Intel HD 4400",
    //        "att_os": {
    //            "brand": "windows",
    //            "version": "10"
    //        },
    //        "att_ram": "8",
    //        "att_ssd": "0",
    //        "att_storage": "1000",
    //        "att_weight": "5.3"
    //    },
    //    {
    //        "name": "Samsung Chromebook 2 11.6 Inch Laptop (Intel Celeron, 2 GB, 16 GB SSD, Silver)",
    //        "price": "249.99",
    //        "image": "http:\/\/ecx.images-amazon.com\/images\/I\/41g63QKnsUL._SL160_.jpg",
    //        "att_gpu": "Intel HD",
    //        "att_screen_size": "11.6",
    //        "att_ram": "2",
    //        "att_storage": "16",
    //        "att_weight": "2.65",
    //        "att_brand": "Samsung",
    //        "att_ssd": "16",
    //        "att_pixels_x": "1366",
    //        "att_pixels_y": "768",
    //        "att_touchscreen": false,
    //        "att_os": {
    //            "brand": "Chrome OS",
    //            "version": "2"
    //        }
    //    },
    //    {
    //        "name": "Apple MacBook Air MJVE2LL\/A 13-inch Laptop (1.6 GHz Intel Core i5,4GB RAM,128 GB SSD Hard Drive, Mac OS X)",
    //        "price": "911.95",
    //        "image": "http:\/\/ecx.images-amazon.com\/images\/I\/31nkqgDl0OL._SL160_.jpg",
    //        "att_brand": "Apple",
    //        "att_screen_size": "13.3",
    //        "att_pixels_x": "1440",
    //        "att_pixels_y": "900",
    //        "att_cpu": "Intel Core i5",
    //        "att_gpu": "Intel HD Graphics 6000",
    //        "att_ram": "4",
    //        "att_touchscreen": false,
    //        "att_ssd": "128",
    //        "att_storage": "128",
    //        "att_weight": "3",
    //        "att_os": {
    //            "brand": "OSX",
    //            "version": "Leopard"
    //        }
    //    }
    ];
})(module.exports);